dist: trusty
sudo: false  # to use container-based infra, see: http://docs.travis-ci.com/user/migrating-from-legacy/

language:
  - python
python:
  - "2.7"

cache:
  directories:
    - download
    - $HOME/.cache/pip
    - $HOME/miniconda/envs/test      # to avoid repetitively setting up Ana/Miniconda environment

before_install:
  - deactivate  # leaving Travis' virtualenv first since otherwise Jupyter/IPython gets confused with conda inside a virtualenv (See: https://github.com/ipython/ipython/issues/8898)
  - mkdir -p download
  - cd download
  - travis_retry wget -c https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -f -p ~/miniconda
  - cd ..
  - export PATH=~/miniconda/bin:$PATH
  - conda update --yes conda
  
script:
  - python numerical_test/Simulate_Extreme_Cases_Jump.py
  - python numerical_test/Simulate_Extreme_Cases_Zero_Epoch.py	
